# Generated by Django 5.0.3 on 2025-08-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeAtCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('company_logo_url', models.URLField()),
                ('employment_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('package_per_annum', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('company_website_url', models.URLField(blank=True, null=True)),
                ('similar_jobs', models.ManyToManyField(blank=True, related_name='is_similar_to', to='jobs.job')),
                ('life_at_company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_link', to='jobs.lifeatcompany')),
                ('skills', models.ManyToManyField(related_name='jobs', to='jobs.skill')),
            ],
        ),
    ]
