# Generated by Django 5.0.3 on 2025-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_life_at_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='similar_jobs',
            field=models.ManyToManyField(blank=True, to='jobs.job'),
        ),
    ]
