# Generated by Django 5.0.3 on 2025-08-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_package_per_annum_alter_job_similar_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='similar_jobs',
            field=models.ManyToManyField(blank=True, to='jobs.job'),
        ),
    ]
