# Generated by Django 5.0.3 on 2025-08-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_similar_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='life_at_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.lifeatcompany'),
        ),
    ]
